-- Seed initial data for SVLNS GDC Multidisciplinary Journal
-- This script populates the database with sample data

-- Insert Editorial Board Members
INSERT INTO editorial_board (first_name, last_name, email, position, affiliation, expertise_areas, bio, order_position) VALUES
('Dr. P.', 'Surekha', 'principal@svlnsgdc.ac.in', 'Editor-in-Chief & Principal', 'Sri Varaha Lakshmi Narsimha Swami Government Degree College', '["Educational Leadership", "Academic Administration", "Higher Education Policy"]', 'Principal and Editor-in-Chief of SVLNS Government Degree College, Bheemunipatnam. Leading the institution with dedication to quality education and social transformation.', 1),
('Dr. K.', 'Ramesh', 'ramesh@svlnsgdc.ac.in', 'Associate Editor - Sciences', 'Department of Physics, SVLNS GDC', '["Physics", "Applied Sciences", "Research Methodology"]', 'Professor and Head, Department of Physics. Specializes in applied physics and interdisciplinary research with focus on coastal environmental studies.', 2),
('Dr. M.', 'Lakshmi', 'lakshmi@svlnsgdc.ac.in', 'Associate Editor - Chemistry', 'Department of Chemistry, SVLNS GDC', '["Analytical Chemistry", "Environmental Chemistry", "Marine Chemistry"]', 'Associate Professor, Department of Chemistry. Expert in analytical and environmental chemistry with special focus on coastal water analysis.', 3),
('Dr. S.', 'Prasad', 'prasad@svlnsgdc.ac.in', 'Associate Editor - Botany', 'Department of Botany, SVLNS GDC', '["Plant Ecology", "Coastal Botany", "Biodiversity Conservation"]', 'Professor, Department of Botany. Research focus on coastal plant ecology and biodiversity conservation in Andhra Pradesh region.', 4),
('Dr. V.', 'Rao', 'vrao@svlnsgdc.ac.in', 'Associate Editor - Zoology', 'Department of Zoology, SVLNS GDC', '["Marine Biology", "Coastal Ecology", "Animal Behavior"]', 'Associate Professor, Department of Zoology. Specializes in marine biology and coastal ecosystem studies with focus on Bay of Bengal marine life.', 5),
('Dr. G.', 'Krishna', 'krishna@svlnsgdc.ac.in', 'Associate Editor - Mathematics', 'Department of Mathematics, SVLNS GDC', '["Applied Mathematics", "Statistics", "Mathematical Modeling"]', 'Professor, Department of Mathematics. Expert in applied mathematics and statistical analysis with applications in environmental and social sciences.', 6),
('Dr. R.', 'Devi', 'rdevi@svlnsgdc.ac.in', 'Associate Editor - English', 'Department of English, SVLNS GDC', '["English Literature", "Linguistics", "Communication Studies"]', 'Associate Professor, Department of English. Research interests in contemporary literature and effective communication in academic writing.', 7),
('Dr. N.', 'Kumar', 'nkumar@svlnsgdc.ac.in', 'Associate Editor - Telugu', 'Department of Telugu, SVLNS GDC', '["Telugu Literature", "Regional Studies", "Cultural Heritage"]', 'Professor, Department of Telugu. Expert in Telugu literature and coastal Andhra Pradesh cultural studies with focus on local traditions.', 8),
('Dr. P.', 'Reddy', 'preddy@svlnsgdc.ac.in', 'Associate Editor - History', 'Department of History, SVLNS GDC', '["Regional History", "Archaeology", "Cultural Studies"]', 'Associate Professor, Department of History. Specializes in regional history of coastal Andhra Pradesh and archaeological studies.', 9),
('Dr. A.', 'Sharma', 'asharma@svlnsgdc.ac.in', 'Associate Editor - Economics', 'Department of Economics, SVLNS GDC', '["Development Economics", "Rural Economics", "Coastal Economy"]', 'Professor, Department of Economics. Focus on development economics and rural studies with emphasis on coastal community development.', 10),
('Dr. B.', 'Murthy', 'bmurthy@svlnsgdc.ac.in', 'Associate Editor - Political Science', 'Department of Political Science, SVLNS GDC', '["Public Administration", "Governance", "Local Government"]', 'Associate Professor, Department of Political Science. Research in governance, public policy, and local government administration.', 11),
('Dr. L.', 'Srinivas', 'lsrinivas@svlnsgdc.ac.in', 'Associate Editor - Commerce', 'Department of Commerce, SVLNS GDC', '["Business Studies", "Financial Management", "Entrepreneurship"]', 'Professor, Department of Commerce. Expert in business studies, financial management, and promoting entrepreneurship in rural areas.', 12),
('Dr. T.', 'Vijaya', 'tvijaya@svlnsgdc.ac.in', 'Associate Editor - Computer Science', 'Department of Computer Science, SVLNS GDC', '["Information Technology", "Digital Systems", "E-Learning"]', 'Assistant Professor, Department of Computer Science. Specializes in IT applications, digital publishing, and e-learning systems.', 13),
('Dr. K.', 'Madhavi', 'kmadhavi@svlnsgdc.ac.in', 'Managing Editor', 'Library & Information Science, SVLNS GDC', '["Library Science", "Information Management", "Research Methodology"]', 'Librarian and Managing Editor. Expert in information management, research methodology, and academic publishing standards.', 14);

-- Insert Faculty Research Profiles
INSERT INTO faculty (first_name, last_name, email, department, position, expertise_areas, research_interests, publications_count, experience_years, phone, office_location) VALUES
('Dr. P.', 'Surekha', 'principal@svlnsgdc.ac.in', 'Administration', 'Principal', '["Educational Leadership", "Academic Administration", "Higher Education Policy"]', 'Educational policy development, institutional governance, and quality assurance in higher education. Focus on rural education development and community engagement.', 25, 20, '8247685902', 'Principal''s Office'),
('Dr. K.', 'Ramesh', 'ramesh@svlnsgdc.ac.in', 'Physics', 'Professor & Head', '["Applied Physics", "Condensed Matter Physics", "Materials Science"]', 'Nanomaterials synthesis and characterization, semiconductor physics, and renewable energy applications. Special focus on solar cell materials and coastal environmental physics.', 42, 18, NULL, 'Physics Department, Room 201'),
('Dr. M.', 'Lakshmi', 'lakshmi@svlnsgdc.ac.in', 'Chemistry', 'Associate Professor', '["Analytical Chemistry", "Environmental Chemistry", "Marine Chemistry"]', 'Water quality analysis of coastal regions, heavy metal contamination studies, and development of eco-friendly analytical methods. Research on Bay of Bengal water chemistry.', 38, 15, NULL, 'Chemistry Lab, Block A'),
('Dr. S.', 'Prasad', 'prasad@svlnsgdc.ac.in', 'Botany', 'Professor', '["Plant Ecology", "Coastal Botany", "Biodiversity Conservation"]', 'Coastal vegetation studies, mangrove ecosystem conservation, and plant adaptation mechanisms in saline environments. Focus on indigenous plant species of Andhra Pradesh coast.', 35, 16, NULL, 'Botany Department, Herbarium'),
('Dr. V.', 'Rao', 'vrao@svlnsgdc.ac.in', 'Zoology', 'Associate Professor', '["Marine Biology", "Coastal Ecology", "Fisheries Science"]', 'Marine biodiversity of Bay of Bengal, fish population dynamics, and impact of climate change on coastal marine ecosystems. Collaborative research with local fishing communities.', 31, 14, NULL, 'Zoology Lab, Block B'),
('Dr. G.', 'Krishna', 'krishna@svlnsgdc.ac.in', 'Mathematics', 'Professor', '["Applied Mathematics", "Statistics", "Mathematical Modeling"]', 'Statistical analysis of environmental data, mathematical modeling of coastal processes, and operations research applications in rural development projects.', 28, 17, NULL, 'Mathematics Department, Room 105'),
('Dr. R.', 'Devi', 'rdevi@svlnsgdc.ac.in', 'English', 'Associate Professor', '["English Literature", "Linguistics", "Communication Studies"]', 'Contemporary Indian English literature, sociolinguistics of coastal communities, and effective communication strategies in multilingual academic environments.', 22, 12, NULL, 'English Department, Room 301'),
('Dr. N.', 'Kumar', 'nkumar@svlnsgdc.ac.in', 'Telugu', 'Professor', '["Telugu Literature", "Regional Studies", "Cultural Heritage"]', 'Classical and modern Telugu literature, oral traditions of coastal Andhra Pradesh, and preservation of regional cultural heritage through digital documentation.', 33, 19, NULL, 'Telugu Department, Room 205'),
('Dr. P.', 'Reddy', 'preddy@svlnsgdc.ac.in', 'History', 'Associate Professor', '["Regional History", "Archaeology", "Cultural Studies"]', 'Historical significance of Bheemunipatnam port, archaeological studies of coastal Andhra Pradesh, and documentation of local historical monuments and traditions.', 26, 13, NULL, 'History Department, Room 102'),
('Dr. A.', 'Sharma', 'asharma@svlnsgdc.ac.in', 'Economics', 'Professor', '["Development Economics", "Rural Economics", "Coastal Economy"]', 'Economic development of coastal communities, impact of fishing industry on local economy, and sustainable development models for rural areas.', 29, 15, NULL, 'Economics Department, Room 203'),
('Dr. B.', 'Murthy', 'bmurthy@svlnsgdc.ac.in', 'Political Science', 'Associate Professor', '["Public Administration", "Governance", "Local Government"]', 'Local governance systems, panchayati raj institutions, and public policy implementation in rural and coastal areas of Andhra Pradesh.', 24, 11, NULL, 'Political Science Department, Room 304'),
('Dr. L.', 'Srinivas', 'lsrinivas@svlnsgdc.ac.in', 'Commerce', 'Professor', '["Business Studies", "Financial Management", "Entrepreneurship"]', 'Small business development in rural areas, microfinance impact studies, and promoting entrepreneurship among coastal communities.', 27, 14, NULL, 'Commerce Department, Room 401'),
('Dr. T.', 'Vijaya', 'tvijaya@svlnsgdc.ac.in', 'Computer Science', 'Assistant Professor', '["Information Technology", "Digital Systems", "E-Learning"]', 'Digital literacy in rural areas, e-learning platform development, and IT applications in education and local governance.', 18, 8, NULL, 'Computer Lab, Block C'),
('Dr. K.', 'Madhavi', 'kmadhavi@svlnsgdc.ac.in', 'Library Science', 'Librarian', '["Library Science", "Information Management", "Digital Archives"]', 'Digital preservation of local historical documents, information literacy programs, and development of institutional repositories for academic research.', 21, 12, NULL, 'Central Library');

-- Insert sample authors (using faculty as authors)
INSERT INTO authors (email, first_name, last_name, affiliation, orcid) VALUES
('ramesh@svlnsgdc.ac.in', 'Dr. K.', 'Ramesh', 'Department of Physics, SVLNS Government Degree College', '0000-0001-2345-6789'),
('lakshmi@svlnsgdc.ac.in', 'Dr. M.', 'Lakshmi', 'Department of Chemistry, SVLNS Government Degree College', '0000-0001-3456-7890'),
('prasad@svlnsgdc.ac.in', 'Dr. S.', 'Prasad', 'Department of Botany, SVLNS Government Degree College', '0000-0001-4567-8901'),
('vrao@svlnsgdc.ac.in', 'Dr. V.', 'Rao', 'Department of Zoology, SVLNS Government Degree College', '0000-0001-5678-9012'),
('krishna@svlnsgdc.ac.in', 'Dr. G.', 'Krishna', 'Department of Mathematics, SVLNS Government Degree College', '0000-0001-6789-0123');

-- Insert the inaugural issue
INSERT INTO issues (volume, issue, year, title, description, publish_date, special_issue, article_count, total_pages) VALUES
(1, 1, 2025, 'Inaugural Issue - Multidisciplinary Research Perspectives', 'The first issue of SVLNS GDC Multidisciplinary Journal, featuring diverse research contributions from faculty and researchers across various disciplines.', '2025-01-15', true, 5, '1-120');

-- Insert sample articles for the inaugural issue
INSERT INTO articles (title, abstract, keywords, article_type, subject_area, status, volume, issue, pages, author_id, co_authors, publication_date, submission_date) VALUES
('Coastal Water Quality Assessment in Bheemunipatnam Region', 'This study presents a comprehensive analysis of water quality parameters in the coastal waters of Bheemunipatnam, Andhra Pradesh. The research examines various physicochemical and biological parameters to assess the environmental health of the coastal ecosystem.', '["water quality", "coastal environment", "Bheemunipatnam", "environmental monitoring"]', 'research', 'Environmental Science', 'published', 1, 1, '1-15', (SELECT id FROM authors WHERE email = 'lakshmi@svlnsgdc.ac.in'), '[{"name": "Dr. V. Rao", "affiliation": "Department of Zoology, SVLNS GDC", "email": "vrao@svlnsgdc.ac.in"}]', '2025-01-15', '2024-11-15'),
('Biodiversity Conservation Strategies for Coastal Mangrove Ecosystems', 'An in-depth study of mangrove biodiversity in the coastal regions of Andhra Pradesh, focusing on conservation strategies and sustainable management practices for these critical ecosystems.', '["mangroves", "biodiversity", "conservation", "coastal ecology"]', 'research', 'Botany', 'published', 1, 1, '16-32', (SELECT id FROM authors WHERE email = 'prasad@svlnsgdc.ac.in'), '[]', '2025-01-15', '2024-11-20'),
('Mathematical Modeling of Coastal Erosion Patterns', 'This paper presents mathematical models to predict and analyze coastal erosion patterns along the Andhra Pradesh coastline, with specific focus on the Bheemunipatnam region.', '["mathematical modeling", "coastal erosion", "environmental mathematics", "predictive analysis"]', 'research', 'Mathematics', 'published', 1, 1, '33-48', (SELECT id FROM authors WHERE email = 'krishna@svlnsgdc.ac.in'), '[{"name": "Dr. K. Ramesh", "affiliation": "Department of Physics, SVLNS GDC", "email": "ramesh@svlnsgdc.ac.in"}]', '2025-01-15', '2024-11-25'),
('Nanomaterials Applications in Solar Energy Harvesting', 'A comprehensive review of nanomaterials and their applications in solar energy harvesting technologies, with emphasis on cost-effective solutions for rural electrification.', '["nanomaterials", "solar energy", "renewable energy", "rural electrification"]', 'review', 'Physics', 'published', 1, 1, '49-68', (SELECT id FROM authors WHERE email = 'ramesh@svlnsgdc.ac.in'), '[]', '2025-01-15', '2024-12-01'),
('Marine Fisheries and Socio-Economic Impact on Coastal Communities', 'An interdisciplinary study examining the relationship between marine fisheries and the socio-economic conditions of coastal communities in the Visakhapatnam district.', '["marine fisheries", "socio-economic impact", "coastal communities", "sustainable development"]', 'research', 'Zoology', 'published', 1, 1, '69-85', (SELECT id FROM authors WHERE email = 'vrao@svlnsgdc.ac.in'), '[{"name": "Dr. A. Sharma", "affiliation": "Department of Economics, SVLNS GDC", "email": "asharma@svlnsgdc.ac.in"}]', '2025-01-15', '2024-12-05');
